version: '2'
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: sh -c "uvicorn src.server.main:app --reload --host 0.0.0.0 --port 5000"
    ports:
      - "8000:8000"
    volumes:
      - transfer-area:/opt/transfer_area/
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    depends_on:
      - api
    volumes:
      - transfer-area:/opt/transfer_area/

volumes:
  transfer-area: