version: '2'
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: sh -c "python -m src.database.generate_db && uvicorn src.server.main:app --reload --host 0.0.0.0 --port 5000"
    environment:
      - PORT=5000
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - transfer-area:/opt/transfer_area/
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    environment:
      - TELEGRAM_TOKEN=
      - CALLBACK_URL=
    depends_on:
      - api
      - db
    volumes:
      - transfer-area:/opt/transfer_area/
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres

volumes:
  transfer-area: